### ISSUE TITLE
HTTP retry

### ISSUE THREAD

**Issue by zhangyoufu** [zhangyoufu/XuanWu-RSS#1]
```
  File ".github/cron.py", line 36, in get
    with urllib.request.urlopen(req, context=ssl_ctx) as rsp:
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
```

**Comment by zhangyoufu** [comment]
再收集一些其它异常姿势

**Comment by zhangyoufu** [comment]
```
[INFO] fetching article list
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/http/client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/http/client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/http/client.py", line 568, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/http/client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".github/cron.py", line 58, in <module>
    for match in re.finditer(r'<a target="_blank" href="([^"]+)" class="W_autocut S_txt1">\s*(.*?)</a>\s*</div>\s*</div>\s*<div class="subinfo_box">\s*<span class="subinfo S_txt2">(\d{4,}) 年 (\d{2}) 月 (\d{2}) 日 (\d{2}):(\d{2})</span>', get('https://weibo.com/p/1006065582522936/wenzhang')):
  File ".github/cron.py", line 37, in get
    return rsp.read().decode('utf-8')
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/http/client.py", line 461, in read
    return self._readall_chunked()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/http/client.py", line 575, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(32609 bytes read)
##[error]Process completed with exit code 1.
```

**Comment by zhangyoufu** [comment]
```
[INFO] logging in Weibo
[DEBUG] Starting new HTTPS connection (1): login.sina.com.cn:443
[DEBUG] https://login.sina.com.cn:443 "GET /sso/prelogin.php?entry=sso&callback=sinaSSOController.preloginCallBack&su=***&rsakt=mod HTTP/1.1" 200 None
[DEBUG] https://login.sina.com.cn:443 "POST /sso/login.php HTTP/1.1" 200 None
[DEBUG] https://login.sina.com.cn:443 "GET /crossdomain2.php?action=login&entry=sso&r=https%3A%2F%2Fpassport.weibo.com%2Fwbsso%2Flogin%3Furl%3Dhttps%253A%252F%252Fwww.weibo.com%252F%26display%3D0%26ticket%3D...%26retcode%3D0&login_time=...&sign=... HTTP/1.1" 200 None
[DEBUG] Starting new HTTPS connection (1): passport.weibo.com:443
[DEBUG] https://passport.weibo.com:443 "GET /wbsso/login?url=https%3A%2F%2Fwww.weibo.com%2F&display=0&ticket=...&retcode=0 HTTP/1.1" 302 None
[DEBUG] Starting new HTTPS connection (1): weibo.com:443
[DEBUG] https://weibo.com:443 "GET /nguide/interest HTTP/1.1" 301 276
[DEBUG] https://www.weibo.com:443 "GET /nguide/interest HTTP/1.1" 302 0
[DEBUG] https://www.weibo.com:443 "GET /nguide/interests HTTP/1.1" 302 None
[DEBUG] Starting new HTTPS connection (1): d.weibo.com:443
##[error]The operation was canceled.
```
6hrs timeout

**Comment by zhangyoufu** [comment]
```
2020-02-17T03:34:32.5774668Z [INFO] fetching article list
2020-02-17T03:34:32.5775025Z [DEBUG] Starting new HTTPS connection (1): www.weibo.com:443
2020-02-17T03:34:35.5821244Z [DEBUG] https://www.weibo.com:443 "GET /p/1006065582522936/wenzhang HTTP/1.1" 200 None
2020-02-17T03:36:38.9322796Z Traceback (most recent call last):
2020-02-17T03:36:38.9341689Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 685, in _update_chunk_length
2020-02-17T03:36:38.9341947Z     self.chunk_left = int(line, 16)
2020-02-17T03:36:38.9342421Z ValueError: invalid literal for int() with base 16: b''
2020-02-17T03:36:38.9342490Z 
2020-02-17T03:36:38.9342610Z During handling of the above exception, another exception occurred:
2020-02-17T03:36:38.9342692Z 
2020-02-17T03:36:38.9342797Z Traceback (most recent call last):
2020-02-17T03:36:38.9343486Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 425, in _error_catcher
2020-02-17T03:36:38.9343661Z     yield
2020-02-17T03:36:38.9344101Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 752, in read_chunked
2020-02-17T03:36:38.9344248Z     self._update_chunk_length()
2020-02-17T03:36:38.9344658Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 689, in _update_chunk_length
2020-02-17T03:36:38.9344834Z     raise httplib.IncompleteRead(line)
2020-02-17T03:36:38.9344960Z http.client.IncompleteRead: IncompleteRead(0 bytes read)
2020-02-17T03:36:38.9345041Z 
2020-02-17T03:36:38.9345156Z During handling of the above exception, another exception occurred:
2020-02-17T03:36:38.9345236Z 
2020-02-17T03:36:38.9345339Z Traceback (most recent call last):
2020-02-17T03:36:38.9345724Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/requests/models.py", line 750, in generate
2020-02-17T03:36:38.9345884Z     for chunk in self.raw.stream(chunk_size, decode_content=True):
2020-02-17T03:36:38.9346264Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 560, in stream
2020-02-17T03:36:38.9346412Z     for line in self.read_chunked(amt, decode_content=decode_content):
2020-02-17T03:36:38.9346824Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 781, in read_chunked
2020-02-17T03:36:38.9346968Z     self._original_response.close()
2020-02-17T03:36:38.9347127Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/contextlib.py", line 131, in __exit__
2020-02-17T03:36:38.9347262Z     self.gen.throw(type, value, traceback)
2020-02-17T03:36:38.9347646Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
2020-02-17T03:36:38.9347838Z     raise ProtocolError("Connection broken: %r" % e, e)
2020-02-17T03:36:38.9348183Z urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2020-02-17T03:36:38.9348255Z 
2020-02-17T03:36:38.9348385Z During handling of the above exception, another exception occurred:
2020-02-17T03:36:38.9348450Z 
2020-02-17T03:36:38.9348553Z Traceback (most recent call last):
2020-02-17T03:36:38.9348829Z   File ".github/cron.py", line 92, in <module>
2020-02-17T03:36:38.9349205Z     body = get('https://www.weibo.com/p/1006065582522936/wenzhang').text
2020-02-17T03:36:38.9349374Z   File ".github/cron.py", line 35, in get
2020-02-17T03:36:38.9349655Z     return request('GET', url, **kwargs)
2020-02-17T03:36:38.9349803Z   File ".github/cron.py", line 32, in request
2020-02-17T03:36:38.9349926Z     return session.request(method, url, **kwargs)
2020-02-17T03:36:38.9350299Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
2020-02-17T03:36:38.9350457Z     resp = self.send(prep, **send_kwargs)
2020-02-17T03:36:38.9350833Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/requests/sessions.py", line 686, in send
2020-02-17T03:36:38.9350978Z     r.content
2020-02-17T03:36:38.9351537Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/requests/models.py", line 828, in content
2020-02-17T03:36:38.9351888Z     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
2020-02-17T03:36:38.9352298Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/requests/models.py", line 753, in generate
2020-02-17T03:36:38.9352472Z     raise ChunkedEncodingError(e)
2020-02-17T03:36:38.9352833Z requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2020-02-17T03:36:38.9452823Z ##[error]Process completed with exit code 1.
2020-02-17T03:36:38.9472540Z Cleaning up orphan processes
```
